# /!\ Warning
# This file is generated by Kriollo, do not edit it manually 

with (import <nixpkgs> {});
mkShell {
    buildInputs = [
        jq
        jq
        maven
        jdk21
        kotlin
    ];
    shellHook = ''
        export JAVA_HOME=${jdk21.home}
        export MAVEN_CONFIG="-s $PWD/.m2/settings.xml"
    '';
}