package org.github.mbarberot.mtg.grimoire.kriollo

// /!\ Warning
// This file is generated by Kriollo, do not edit it manually 

import kotlin.annotation.AnnotationRetention.*
import kotlin.annotation.AnnotationTarget.*

@Generated("Generated by Kriollo")
@Retention(RUNTIME)
@Target(CLASS)
annotation class Generated(
    val value: String
)
