package org.github.mbarberot.mtg.grimoire

// /!\ Warning
// This file is generated by Kriollo, do not edit it manually 

import org.github.mbarberot.mtg.grimoire.kriollo.Generated

@Generated("Generated by Kriollo")
object MtgGrimoireVersion {
    const val VERSION = "2026.0.0"
}